"""
Django settings for pod_manager project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from .middleware import *
import pymysql
from .Config import * 

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^_(xflmcn+cw(uj0^%^%u*y3wy_0kme66$o2lpj06$bon8i&28'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = True

#20171124, Vena_Ho, test, Begin
#ALLOWED_HOSTS = []
#ALLOWED_HOSTS = ['192.168.11.113',
#                 '192.168.2.110',
#                 '127.0.0.1',
#                 'localhost',
#                 '10.3.0.7',
#                 '10.3.0.8',
#                 '10.3.0.9',
#                 '10.3.0.10']
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'bootstrap3',
    'social_django',

    'pod_manager.test',
    #'pod_manager.management',
    'pod_manager.monitor',
    #'pod_manager.monitor.dc_back',
    #'pod_manager.monitor.dc_left',
    #'pod_manager.monitor.dc_main',
    #'pod_manager.monitor.dc_right',
    #'pod_manager.network',
    'pod_manager.podmsetup',
    #'pod_manager.systems',
    #'pod_manager.curlform',
    #'pod_manager.ipmitool',
    'pod_manager.tmsadmin',
    #'pod_manager.as4610',
    #'pod_manager.as5812',
    #'pod_manager.sau5081',
    #'pod_manager.atnurllib',
    #'pod_manager.ansible',
    'pod_manager.components',
    'pod_manager.sonic',
    'pod_manager.personal_settings',
    #'pod_manager.search',
    'pod_manager.telco',
    'pod_manager.data_center',
    'pod_manager.project_management',
    'pod_manager.dms',
    
    'application',
    'createform',
    'rest_framework',
    'atnutils.snippets',
    'django.contrib.admin',
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        #'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pod_manager.middleware.MySocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'pod_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates').replace('\\', '/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pod_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USER,     # 用户名，可以自己创建用户
        'PASSWORD': DATABASE_PASSWORD,  # 密码
        'HOST' : DATABASE_HOST,
        'TEST': {
                'CHARSET': 'utf8',
                'COLLATION': 'utf8_general_ci',
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

CSRF_COOKIE_NAME = "XSRF-TOKEN"

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = False
LOGIN_REDIRECT_URL = '/'

SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '792760183106-38o275o8j07ucacp13lkumud6ipv7b5t.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'xn0VAXRfO7rtS3TxGLK3DYLB'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 25
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = 'Whatever <whatever@example.com>'
