# Generated by Django 2.2 on 2019-06-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetid', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=24)),
                ('commonname', models.CharField(max_length=30)),
                ('expired', models.CharField(blank=True, max_length=4)),
                ('modelnum', models.CharField(blank=True, max_length=30)),
                ('modelid', models.CharField(blank=True, max_length=30)),
                ('swversion', models.CharField(blank=True, max_length=16)),
                ('serialno', models.CharField(blank=True, max_length=30)),
                ('longtitude', models.CharField(blank=True, max_length=16)),
                ('latitude', models.CharField(blank=True, max_length=16)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('netmask', models.CharField(blank=True, max_length=16)),
                ('ip6', models.CharField(max_length=30)),
                ('pos_inrack', models.IntegerField(null=True)),
                ('rackid', models.IntegerField(null=True)),
                ('rowid', models.IntegerField(null=True)),
                ('roomid', models.IntegerField(null=True)),
                ('fl_sessid', models.IntegerField(null=True)),
                ('addrid', models.IntegerField(null=True)),
                ('siteid', models.IntegerField(null=True)),
                ('corpid', models.IntegerField(null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=16)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip', models.IntegerField(null=True)),
                ('country', models.CharField(blank=True, max_length=24)),
            ],
        ),
    ]
